# Generated by Django 5.1 on 2024-08-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondages', '0002_about_contact_remove_service_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
        migrations.AlterModelOptions(
            name='rendez_vous',
            options={'verbose_name': 'Rendez-Vous', 'verbose_name_plural': 'Rendez-Vous'},
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
