# Generated by Django 5.1 on 2024-08-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondages', '0003_alter_avis_options_alter_rendez_vous_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
