# Generated by Django 5.1 on 2024-08-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondages', '0006_methode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Methode',
        ),
    ]
